<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Table [
	<!ATTLIST Table name CDATA "">
	<!ELEMENT Table (Row+)>
		<!ELEMENT Row (Depth, DENB, CADE)>
		<!ELEMENT Depth (#PCDATA)>
		<!ELEMENT DENB (#PCDATA)>
		<!ELEMENT CADE (#PCDATA)>
]>
<Table name="TestTable">
	<Row>
		<Depth>0</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>0.1</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>0.2</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>0.3</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>0.4</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>0.5</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>0.6</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>0.7</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>0.8</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>0.9</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>1</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>1.1</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>1.2</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>1.3</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>1.4</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>1.5</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>1.6</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>1.7</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>1.8</Depth>
		<DENB>-999.25</DENB>
		<CADE>-999.25</CADE>
	</Row>
	<Row>
		<Depth>1.9</Depth>
		<DENB>-999.25</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>2</Depth>
		<DENB>-999.25</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>2.1</Depth>
		<DENB>-999.25</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>2.2</Depth>
		<DENB>-999.25</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>2.3</Depth>
		<DENB>-999.25</DENB>
		<CADE>106.25</CADE>
	</Row>
	<Row>
		<Depth>2.4</Depth>
		<DENB>-999.25</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>2.5</Depth>
		<DENB>-999.25</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>2.6</Depth>
		<DENB>-999.25</DENB>
		<CADE>106.3</CADE>
	</Row>
	<Row>
		<Depth>2.7</Depth>
		<DENB>-999.25</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>2.8</Depth>
		<DENB>2.69</DENB>
		<CADE>106.25</CADE>
	</Row>
	<Row>
		<Depth>2.9</Depth>
		<DENB>2.69</DENB>
		<CADE>106.26</CADE>
	</Row>
	<Row>
		<Depth>3</Depth>
		<DENB>2.68</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>3.1</Depth>
		<DENB>2.67</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>3.2</Depth>
		<DENB>2.69</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>3.3</Depth>
		<DENB>2.73</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>3.4</Depth>
		<DENB>2.77</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>3.5</Depth>
		<DENB>2.8</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>3.6</Depth>
		<DENB>2.79</DENB>
		<CADE>106.3</CADE>
	</Row>
	<Row>
		<Depth>3.7</Depth>
		<DENB>2.78</DENB>
		<CADE>106.33</CADE>
	</Row>
	<Row>
		<Depth>3.8</Depth>
		<DENB>2.78</DENB>
		<CADE>106.32</CADE>
	</Row>
	<Row>
		<Depth>3.9</Depth>
		<DENB>2.79</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>4</Depth>
		<DENB>2.79</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>4.1</Depth>
		<DENB>2.79</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>4.2</Depth>
		<DENB>2.79</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>4.3</Depth>
		<DENB>2.79</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>4.4</Depth>
		<DENB>2.8</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>4.5</Depth>
		<DENB>2.8</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>4.6</Depth>
		<DENB>2.82</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>4.7</Depth>
		<DENB>2.82</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>4.8</Depth>
		<DENB>2.82</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>4.9</Depth>
		<DENB>2.82</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>5</Depth>
		<DENB>2.82</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>5.1</Depth>
		<DENB>2.82</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>5.2</Depth>
		<DENB>2.81</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>5.3</Depth>
		<DENB>2.82</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>5.4</Depth>
		<DENB>2.83</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>5.5</Depth>
		<DENB>2.85</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>5.6</Depth>
		<DENB>2.85</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>5.7</Depth>
		<DENB>2.83</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>5.8</Depth>
		<DENB>2.81</DENB>
		<CADE>106.26</CADE>
	</Row>
	<Row>
		<Depth>5.9</Depth>
		<DENB>2.83</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>6</Depth>
		<DENB>2.84</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>6.1</Depth>
		<DENB>2.84</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>6.2</Depth>
		<DENB>2.81</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>6.3</Depth>
		<DENB>2.8</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>6.4</Depth>
		<DENB>2.76</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>6.5</Depth>
		<DENB>2.74</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>6.6</Depth>
		<DENB>2.69</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>6.7</Depth>
		<DENB>2.62</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>6.8</Depth>
		<DENB>2.59</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>6.9</Depth>
		<DENB>2.53</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>7</Depth>
		<DENB>2.41</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>7.1</Depth>
		<DENB>2.27</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>7.2</Depth>
		<DENB>2.13</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>7.3</Depth>
		<DENB>2.05</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>7.4</Depth>
		<DENB>2.1</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>7.5</Depth>
		<DENB>2.3</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>7.6</Depth>
		<DENB>2.46</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>7.7</Depth>
		<DENB>2.41</DENB>
		<CADE>106.25</CADE>
	</Row>
	<Row>
		<Depth>7.8</Depth>
		<DENB>2.17</DENB>
		<CADE>106.23</CADE>
	</Row>
	<Row>
		<Depth>7.9</Depth>
		<DENB>1.95</DENB>
		<CADE>106.23</CADE>
	</Row>
	<Row>
		<Depth>8</Depth>
		<DENB>1.85</DENB>
		<CADE>106.3</CADE>
	</Row>
	<Row>
		<Depth>8.1</Depth>
		<DENB>1.96</DENB>
		<CADE>106.68</CADE>
	</Row>
	<Row>
		<Depth>8.2</Depth>
		<DENB>2.19</DENB>
		<CADE>107.32</CADE>
	</Row>
	<Row>
		<Depth>8.3</Depth>
		<DENB>2.4</DENB>
		<CADE>107.93</CADE>
	</Row>
	<Row>
		<Depth>8.4</Depth>
		<DENB>2.49</DENB>
		<CADE>108.24</CADE>
	</Row>
	<Row>
		<Depth>8.5</Depth>
		<DENB>2.48</DENB>
		<CADE>108.23</CADE>
	</Row>
	<Row>
		<Depth>8.6</Depth>
		<DENB>2.5</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>8.7</Depth>
		<DENB>2.55</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>8.8</Depth>
		<DENB>2.63</DENB>
		<CADE>108.23</CADE>
	</Row>
	<Row>
		<Depth>8.9</Depth>
		<DENB>2.68</DENB>
		<CADE>108.25</CADE>
	</Row>
	<Row>
		<Depth>9</Depth>
		<DENB>2.69</DENB>
		<CADE>108.24</CADE>
	</Row>
	<Row>
		<Depth>9.1</Depth>
		<DENB>2.69</DENB>
		<CADE>108.23</CADE>
	</Row>
	<Row>
		<Depth>9.2</Depth>
		<DENB>2.67</DENB>
		<CADE>108.2</CADE>
	</Row>
	<Row>
		<Depth>9.3</Depth>
		<DENB>2.63</DENB>
		<CADE>108.2</CADE>
	</Row>
	<Row>
		<Depth>9.4</Depth>
		<DENB>2.61</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>9.5</Depth>
		<DENB>2.63</DENB>
		<CADE>108.24</CADE>
	</Row>
	<Row>
		<Depth>9.6</Depth>
		<DENB>2.67</DENB>
		<CADE>108.23</CADE>
	</Row>
	<Row>
		<Depth>9.7</Depth>
		<DENB>2.68</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>9.8</Depth>
		<DENB>2.71</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>9.9</Depth>
		<DENB>2.74</DENB>
		<CADE>108.23</CADE>
	</Row>
	<Row>
		<Depth>10</Depth>
		<DENB>2.72</DENB>
		<CADE>108.21</CADE>
	</Row>
	<Row>
		<Depth>10.1</Depth>
		<DENB>2.68</DENB>
		<CADE>108.19</CADE>
	</Row>
	<Row>
		<Depth>10.2</Depth>
		<DENB>2.64</DENB>
		<CADE>108.19</CADE>
	</Row>
	<Row>
		<Depth>10.3</Depth>
		<DENB>2.62</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>10.4</Depth>
		<DENB>2.6</DENB>
		<CADE>108.23</CADE>
	</Row>
	<Row>
		<Depth>10.5</Depth>
		<DENB>2.6</DENB>
		<CADE>108.21</CADE>
	</Row>
	<Row>
		<Depth>10.6</Depth>
		<DENB>2.61</DENB>
		<CADE>108.17</CADE>
	</Row>
	<Row>
		<Depth>10.7</Depth>
		<DENB>2.62</DENB>
		<CADE>108.16</CADE>
	</Row>
	<Row>
		<Depth>10.8</Depth>
		<DENB>2.62</DENB>
		<CADE>108.18</CADE>
	</Row>
	<Row>
		<Depth>10.9</Depth>
		<DENB>2.65</DENB>
		<CADE>108.2</CADE>
	</Row>
	<Row>
		<Depth>11</Depth>
		<DENB>2.66</DENB>
		<CADE>108.23</CADE>
	</Row>
	<Row>
		<Depth>11.1</Depth>
		<DENB>2.65</DENB>
		<CADE>108.27</CADE>
	</Row>
	<Row>
		<Depth>11.2</Depth>
		<DENB>2.63</DENB>
		<CADE>108.24</CADE>
	</Row>
	<Row>
		<Depth>11.3</Depth>
		<DENB>2.63</DENB>
		<CADE>108.24</CADE>
	</Row>
	<Row>
		<Depth>11.4</Depth>
		<DENB>2.66</DENB>
		<CADE>108.21</CADE>
	</Row>
	<Row>
		<Depth>11.5</Depth>
		<DENB>2.7</DENB>
		<CADE>108.23</CADE>
	</Row>
	<Row>
		<Depth>11.6</Depth>
		<DENB>2.77</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>11.7</Depth>
		<DENB>2.79</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>11.8</Depth>
		<DENB>2.8</DENB>
		<CADE>108.21</CADE>
	</Row>
	<Row>
		<Depth>11.9</Depth>
		<DENB>2.78</DENB>
		<CADE>108.2</CADE>
	</Row>
	<Row>
		<Depth>12</Depth>
		<DENB>2.77</DENB>
		<CADE>108.21</CADE>
	</Row>
	<Row>
		<Depth>12.1</Depth>
		<DENB>2.75</DENB>
		<CADE>108.2</CADE>
	</Row>
	<Row>
		<Depth>12.2</Depth>
		<DENB>2.75</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>12.3</Depth>
		<DENB>2.76</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>12.4</Depth>
		<DENB>2.78</DENB>
		<CADE>108.24</CADE>
	</Row>
	<Row>
		<Depth>12.5</Depth>
		<DENB>2.8</DENB>
		<CADE>108.25</CADE>
	</Row>
	<Row>
		<Depth>12.6</Depth>
		<DENB>2.8</DENB>
		<CADE>108.23</CADE>
	</Row>
	<Row>
		<Depth>12.7</Depth>
		<DENB>2.81</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>12.8</Depth>
		<DENB>2.8</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>12.9</Depth>
		<DENB>2.79</DENB>
		<CADE>108.24</CADE>
	</Row>
	<Row>
		<Depth>13</Depth>
		<DENB>2.8</DENB>
		<CADE>108.24</CADE>
	</Row>
	<Row>
		<Depth>13.1</Depth>
		<DENB>2.8</DENB>
		<CADE>108.24</CADE>
	</Row>
	<Row>
		<Depth>13.2</Depth>
		<DENB>2.81</DENB>
		<CADE>108.24</CADE>
	</Row>
	<Row>
		<Depth>13.3</Depth>
		<DENB>2.81</DENB>
		<CADE>108.23</CADE>
	</Row>
	<Row>
		<Depth>13.4</Depth>
		<DENB>2.81</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>13.5</Depth>
		<DENB>2.8</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>13.6</Depth>
		<DENB>2.8</DENB>
		<CADE>108.21</CADE>
	</Row>
	<Row>
		<Depth>13.7</Depth>
		<DENB>2.82</DENB>
		<CADE>108.19</CADE>
	</Row>
	<Row>
		<Depth>13.8</Depth>
		<DENB>2.84</DENB>
		<CADE>108.18</CADE>
	</Row>
	<Row>
		<Depth>13.9</Depth>
		<DENB>2.84</DENB>
		<CADE>108.22</CADE>
	</Row>
	<Row>
		<Depth>14</Depth>
		<DENB>2.83</DENB>
		<CADE>108.18</CADE>
	</Row>
	<Row>
		<Depth>14.1</Depth>
		<DENB>2.82</DENB>
		<CADE>107.53</CADE>
	</Row>
	<Row>
		<Depth>14.2</Depth>
		<DENB>2.82</DENB>
		<CADE>106.85</CADE>
	</Row>
	<Row>
		<Depth>14.3</Depth>
		<DENB>2.8</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>14.4</Depth>
		<DENB>2.79</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>14.5</Depth>
		<DENB>2.76</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>14.6</Depth>
		<DENB>2.76</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>14.7</Depth>
		<DENB>2.77</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>14.8</Depth>
		<DENB>2.81</DENB>
		<CADE>106.3</CADE>
	</Row>
	<Row>
		<Depth>14.9</Depth>
		<DENB>2.84</DENB>
		<CADE>106.33</CADE>
	</Row>
	<Row>
		<Depth>15</Depth>
		<DENB>2.85</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>15.1</Depth>
		<DENB>2.84</DENB>
		<CADE>106.32</CADE>
	</Row>
	<Row>
		<Depth>15.2</Depth>
		<DENB>2.82</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>15.3</Depth>
		<DENB>2.81</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>15.4</Depth>
		<DENB>2.8</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>15.5</Depth>
		<DENB>2.81</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>15.6</Depth>
		<DENB>2.82</DENB>
		<CADE>106.3</CADE>
	</Row>
	<Row>
		<Depth>15.7</Depth>
		<DENB>2.85</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>15.8</Depth>
		<DENB>2.86</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>15.9</Depth>
		<DENB>2.84</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>16</Depth>
		<DENB>2.8</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>16.1</Depth>
		<DENB>2.78</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>16.2</Depth>
		<DENB>2.79</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>16.3</Depth>
		<DENB>2.79</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>16.4</Depth>
		<DENB>2.81</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>16.5</Depth>
		<DENB>2.81</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>16.6</Depth>
		<DENB>2.83</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>16.7</Depth>
		<DENB>2.84</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>16.8</Depth>
		<DENB>2.83</DENB>
		<CADE>106.3</CADE>
	</Row>
	<Row>
		<Depth>16.9</Depth>
		<DENB>2.83</DENB>
		<CADE>106.33</CADE>
	</Row>
	<Row>
		<Depth>17</Depth>
		<DENB>2.84</DENB>
		<CADE>106.34</CADE>
	</Row>
	<Row>
		<Depth>17.1</Depth>
		<DENB>2.85</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>17.2</Depth>
		<DENB>2.86</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>17.3</Depth>
		<DENB>2.9</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>17.4</Depth>
		<DENB>2.94</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>17.5</Depth>
		<DENB>2.95</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>17.6</Depth>
		<DENB>2.94</DENB>
		<CADE>106.3</CADE>
	</Row>
	<Row>
		<Depth>17.7</Depth>
		<DENB>2.93</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>17.8</Depth>
		<DENB>2.92</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>17.9</Depth>
		<DENB>2.91</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>18</Depth>
		<DENB>2.9</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>18.1</Depth>
		<DENB>2.91</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>18.2</Depth>
		<DENB>2.9</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>18.3</Depth>
		<DENB>2.91</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>18.4</Depth>
		<DENB>2.89</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>18.5</Depth>
		<DENB>2.9</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>18.6</Depth>
		<DENB>2.91</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>18.7</Depth>
		<DENB>2.95</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>18.8</Depth>
		<DENB>2.96</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>18.9</Depth>
		<DENB>2.95</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>19</Depth>
		<DENB>2.92</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>19.1</Depth>
		<DENB>2.91</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>19.2</Depth>
		<DENB>2.9</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>19.3</Depth>
		<DENB>2.93</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>19.4</Depth>
		<DENB>2.95</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>19.5</Depth>
		<DENB>2.95</DENB>
		<CADE>106.25</CADE>
	</Row>
	<Row>
		<Depth>19.6</Depth>
		<DENB>2.94</DENB>
		<CADE>106.25</CADE>
	</Row>
	<Row>
		<Depth>19.7</Depth>
		<DENB>2.93</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>19.8</Depth>
		<DENB>2.91</DENB>
		<CADE>106.33</CADE>
	</Row>
	<Row>
		<Depth>19.9</Depth>
		<DENB>2.91</DENB>
		<CADE>106.33</CADE>
	</Row>
	<Row>
		<Depth>20</Depth>
		<DENB>2.91</DENB>
		<CADE>106.32</CADE>
	</Row>
	<Row>
		<Depth>20.1</Depth>
		<DENB>2.92</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>20.2</Depth>
		<DENB>2.94</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>20.3</Depth>
		<DENB>2.96</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>20.4</Depth>
		<DENB>2.98</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>20.5</Depth>
		<DENB>2.96</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>20.6</Depth>
		<DENB>2.95</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>20.7</Depth>
		<DENB>2.94</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>20.8</Depth>
		<DENB>2.93</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>20.9</Depth>
		<DENB>2.94</DENB>
		<CADE>106.26</CADE>
	</Row>
	<Row>
		<Depth>21</Depth>
		<DENB>2.95</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>21.1</Depth>
		<DENB>2.98</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>21.2</Depth>
		<DENB>2.99</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>21.3</Depth>
		<DENB>3</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>21.4</Depth>
		<DENB>3</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>21.5</Depth>
		<DENB>3</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>21.6</Depth>
		<DENB>2.98</DENB>
		<CADE>106.33</CADE>
	</Row>
	<Row>
		<Depth>21.7</Depth>
		<DENB>2.96</DENB>
		<CADE>106.33</CADE>
	</Row>
	<Row>
		<Depth>21.8</Depth>
		<DENB>2.93</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>21.9</Depth>
		<DENB>2.91</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>22</Depth>
		<DENB>2.91</DENB>
		<CADE>106.26</CADE>
	</Row>
	<Row>
		<Depth>22.1</Depth>
		<DENB>2.91</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>22.2</Depth>
		<DENB>2.92</DENB>
		<CADE>106.26</CADE>
	</Row>
	<Row>
		<Depth>22.3</Depth>
		<DENB>2.92</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>22.4</Depth>
		<DENB>2.93</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>22.5</Depth>
		<DENB>2.93</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>22.6</Depth>
		<DENB>2.93</DENB>
		<CADE>106.3</CADE>
	</Row>
	<Row>
		<Depth>22.7</Depth>
		<DENB>2.93</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>22.8</Depth>
		<DENB>2.92</DENB>
		<CADE>106.25</CADE>
	</Row>
	<Row>
		<Depth>22.9</Depth>
		<DENB>2.9</DENB>
		<CADE>106.26</CADE>
	</Row>
	<Row>
		<Depth>23</Depth>
		<DENB>2.95</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>23.1</Depth>
		<DENB>3.03</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>23.2</Depth>
		<DENB>3.07</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>23.3</Depth>
		<DENB>3.03</DENB>
		<CADE>106.33</CADE>
	</Row>
	<Row>
		<Depth>23.4</Depth>
		<DENB>2.95</DENB>
		<CADE>106.3</CADE>
	</Row>
	<Row>
		<Depth>23.5</Depth>
		<DENB>2.92</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>23.6</Depth>
		<DENB>2.91</DENB>
		<CADE>106.26</CADE>
	</Row>
	<Row>
		<Depth>23.7</Depth>
		<DENB>2.93</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>23.8</Depth>
		<DENB>2.95</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>23.9</Depth>
		<DENB>2.96</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>24</Depth>
		<DENB>2.97</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>24.1</Depth>
		<DENB>2.95</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>24.2</Depth>
		<DENB>2.95</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>24.3</Depth>
		<DENB>2.95</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>24.4</Depth>
		<DENB>2.96</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>24.5</Depth>
		<DENB>2.98</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>24.6</Depth>
		<DENB>2.99</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>24.7</Depth>
		<DENB>2.98</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>24.8</Depth>
		<DENB>2.97</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>24.9</Depth>
		<DENB>2.98</DENB>
		<CADE>106.31</CADE>
	</Row>
	<Row>
		<Depth>25</Depth>
		<DENB>3</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>25.1</Depth>
		<DENB>3.01</DENB>
		<CADE>106.3</CADE>
	</Row>
	<Row>
		<Depth>25.2</Depth>
		<DENB>3.02</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>25.3</Depth>
		<DENB>3.03</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>25.4</Depth>
		<DENB>3.03</DENB>
		<CADE>106.28</CADE>
	</Row>
	<Row>
		<Depth>25.5</Depth>
		<DENB>3.02</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>25.6</Depth>
		<DENB>3.01</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>25.7</Depth>
		<DENB>3.01</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>25.8</Depth>
		<DENB>3</DENB>
		<CADE>106.27</CADE>
	</Row>
	<Row>
		<Depth>25.9</Depth>
		<DENB>2.97</DENB>
		<CADE>106.35</CADE>
	</Row>
	<Row>
		<Depth>26</Depth>
		<DENB>2.95</DENB>
		<CADE>106.88</CADE>
	</Row>
	<Row>
		<Depth>26.1</Depth>
		<DENB>2.92</DENB>
		<CADE>107.54</CADE>
	</Row>
	<Row>
		<Depth>26.2</Depth>
		<DENB>2.9</DENB>
		<CADE>108.09</CADE>
	</Row>
	<Row>
		<Depth>26.3</Depth>
		<DENB>2.9</DENB>
		<CADE>108.23</CADE>
	</Row>
	<Row>
		<Depth>26.4</Depth>
		<DENB>2.87</DENB>
		<CADE>108.53</CADE>
	</Row>
	<Row>
		<Depth>26.5</Depth>
		<DENB>2.73</DENB>
		<CADE>109.82</CADE>
	</Row>
	<Row>
		<Depth>26.6</Depth>
		<DENB>2.54</DENB>
		<CADE>111.41</CADE>
	</Row>
	<Row>
		<Depth>26.7</Depth>
		<DENB>2.39</DENB>
		<CADE>112.79</CADE>
	</Row>
	<Row>
		<Depth>26.8</Depth>
		<DENB>2.36</DENB>
		<CADE>113.36</CADE>
	</Row>
	<Row>
		<Depth>26.9</Depth>
		<DENB>2.37</DENB>
		<CADE>113.88</CADE>
	</Row>
	<Row>
		<Depth>27</Depth>
		<DENB>2.37</DENB>
		<CADE>114.38</CADE>
	</Row>
	<Row>
		<Depth>27.1</Depth>
		<DENB>2.37</DENB>
		<CADE>114.7</CADE>
	</Row>
	<Row>
		<Depth>27.2</Depth>
		<DENB>2.36</DENB>
		<CADE>114.76</CADE>
	</Row>
	<Row>
		<Depth>27.3</Depth>
		<DENB>2.36</DENB>
		<CADE>114.78</CADE>
	</Row>
	<Row>
		<Depth>27.4</Depth>
		<DENB>2.36</DENB>
		<CADE>114.79</CADE>
	</Row>
	<Row>
		<Depth>27.5</Depth>
		<DENB>2.37</DENB>
		<CADE>114.7</CADE>
	</Row>
	<Row>
		<Depth>27.6</Depth>
		<DENB>2.38</DENB>
		<CADE>114.42</CADE>
	</Row>
	<Row>
		<Depth>27.7</Depth>
		<DENB>2.41</DENB>
		<CADE>113.96</CADE>
	</Row>
	<Row>
		<Depth>27.8</Depth>
		<DENB>2.43</DENB>
		<CADE>113.53</CADE>
	</Row>
	<Row>
		<Depth>27.9</Depth>
		<DENB>2.44</DENB>
		<CADE>113.42</CADE>
	</Row>
	<Row>
		<Depth>28</Depth>
		<DENB>2.4</DENB>
		<CADE>113.71</CADE>
	</Row>
	<Row>
		<Depth>28.1</Depth>
		<DENB>2.36</DENB>
		<CADE>114.15</CADE>
	</Row>
	<Row>
		<Depth>28.2</Depth>
		<DENB>2.34</DENB>
		<CADE>114.64</CADE>
	</Row>
	<Row>
		<Depth>28.3</Depth>
		<DENB>2.33</DENB>
		<CADE>115.1</CADE>
	</Row>
	<Row>
		<Depth>28.4</Depth>
		<DENB>2.33</DENB>
		<CADE>115.43</CADE>
	</Row>
	<Row>
		<Depth>28.5</Depth>
		<DENB>2.31</DENB>
		<CADE>115.59</CADE>
	</Row>
	<Row>
		<Depth>28.6</Depth>
		<DENB>2.31</DENB>
		<CADE>115.68</CADE>
	</Row>
	<Row>
		<Depth>28.7</Depth>
		<DENB>2.32</DENB>
		<CADE>116.05</CADE>
	</Row>
	<Row>
		<Depth>28.8</Depth>
		<DENB>2.35</DENB>
		<CADE>116.45</CADE>
	</Row>
	<Row>
		<Depth>28.9</Depth>
		<DENB>2.36</DENB>
		<CADE>116.75</CADE>
	</Row>
	<Row>
		<Depth>29</Depth>
		<DENB>2.36</DENB>
		<CADE>116.76</CADE>
	</Row>
	<Row>
		<Depth>29.1</Depth>
		<DENB>2.35</DENB>
		<CADE>116.76</CADE>
	</Row>
	<Row>
		<Depth>29.2</Depth>
		<DENB>2.35</DENB>
		<CADE>116.81</CADE>
	</Row>
	<Row>
		<Depth>29.3</Depth>
		<DENB>2.35</DENB>
		<CADE>117.06</CADE>
	</Row>
	<Row>
		<Depth>29.4</Depth>
		<DENB>2.36</DENB>
		<CADE>117.46</CADE>
	</Row>
	<Row>
		<Depth>29.5</Depth>
		<DENB>2.37</DENB>
		<CADE>117.82</CADE>
	</Row>
	<Row>
		<Depth>29.6</Depth>
		<DENB>2.37</DENB>
		<CADE>118.02</CADE>
	</Row>
	<Row>
		<Depth>29.7</Depth>
		<DENB>2.38</DENB>
		<CADE>118.01</CADE>
	</Row>
	<Row>
		<Depth>29.8</Depth>
		<DENB>2.37</DENB>
		<CADE>118.03</CADE>
	</Row>
	<Row>
		<Depth>29.9</Depth>
		<DENB>2.35</DENB>
		<CADE>118.03</CADE>
	</Row>
	<Row>
		<Depth>30</Depth>
		<DENB>2.34</DENB>
		<CADE>118.05</CADE>
	</Row>
	<Row>
		<Depth>30.1</Depth>
		<DENB>2.32</DENB>
		<CADE>118.04</CADE>
	</Row>
	<Row>
		<Depth>30.2</Depth>
		<DENB>2.32</DENB>
		<CADE>118.02</CADE>
	</Row>
	<Row>
		<Depth>30.3</Depth>
		<DENB>2.34</DENB>
		<CADE>118.05</CADE>
	</Row>
	<Row>
		<Depth>30.4</Depth>
		<DENB>2.36</DENB>
		<CADE>118.05</CADE>
	</Row>
	<Row>
		<Depth>30.5</Depth>
		<DENB>2.38</DENB>
		<CADE>118.06</CADE>
	</Row>
	<Row>
		<Depth>30.6</Depth>
		<DENB>2.37</DENB>
		<CADE>118.03</CADE>
	</Row>
	<Row>
		<Depth>30.7</Depth>
		<DENB>2.37</DENB>
		<CADE>118.04</CADE>
	</Row>
	<Row>
		<Depth>30.8</Depth>
		<DENB>2.37</DENB>
		<CADE>118.01</CADE>
	</Row>
	<Row>
		<Depth>30.9</Depth>
		<DENB>2.37</DENB>
		<CADE>118.02</CADE>
	</Row>
	<Row>
		<Depth>31</Depth>
		<DENB>2.37</DENB>
		<CADE>118.01</CADE>
	</Row>
	<Row>
		<Depth>31.1</Depth>
		<DENB>2.28</DENB>
		<CADE>118.34</CADE>
	</Row>
	<Row>
		<Depth>31.2</Depth>
		<DENB>2.2</DENB>
		<CADE>119.05</CADE>
	</Row>
	<Row>
		<Depth>31.3</Depth>
		<DENB>2.17</DENB>
		<CADE>118.75</CADE>
	</Row>
	<Row>
		<Depth>31.4</Depth>
		<DENB>2.25</DENB>
		<CADE>117.72</CADE>
	</Row>
	<Row>
		<Depth>31.5</Depth>
		<DENB>2.32</DENB>
		<CADE>116.29</CADE>
	</Row>
	<Row>
		<Depth>31.6</Depth>
		<DENB>2.34</DENB>
		<CADE>115.71</CADE>
	</Row>
	<Row>
		<Depth>31.7</Depth>
		<DENB>2.36</DENB>
		<CADE>115.25</CADE>
	</Row>
	<Row>
		<Depth>31.8</Depth>
		<DENB>2.39</DENB>
		<CADE>114.81</CADE>
	</Row>
	<Row>
		<Depth>31.9</Depth>
		<DENB>2.41</DENB>
		<CADE>114.48</CADE>
	</Row>
	<Row>
		<Depth>32</Depth>
		<DENB>2.4</DENB>
		<CADE>114.44</CADE>
	</Row>
	<Row>
		<Depth>32.1</Depth>
		<DENB>2.37</DENB>
		<CADE>114.3</CADE>
	</Row>
	<Row>
		<Depth>32.2</Depth>
		<DENB>2.35</DENB>
		<CADE>114.03</CADE>
	</Row>
	<Row>
		<Depth>32.3</Depth>
		<DENB>2.35</DENB>
		<CADE>113.76</CADE>
	</Row>
	<Row>
		<Depth>32.4</Depth>
		<DENB>2.37</DENB>
		<CADE>113.57</CADE>
	</Row>
	<Row>
		<Depth>32.5</Depth>
		<DENB>2.39</DENB>
		<CADE>113.6</CADE>
	</Row>
	<Row>
		<Depth>32.6</Depth>
		<DENB>2.4</DENB>
		<CADE>113.78</CADE>
	</Row>
	<Row>
		<Depth>32.7</Depth>
		<DENB>2.4</DENB>
		<CADE>114.09</CADE>
	</Row>
	<Row>
		<Depth>32.8</Depth>
		<DENB>2.39</DENB>
		<CADE>114.35</CADE>
	</Row>
	<Row>
		<Depth>32.9</Depth>
		<DENB>2.4</DENB>
		<CADE>114.37</CADE>
	</Row>
	<Row>
		<Depth>33</Depth>
		<DENB>2.41</DENB>
		<CADE>113.96</CADE>
	</Row>
	<Row>
		<Depth>33.1</Depth>
		<DENB>2.42</DENB>
		<CADE>113.57</CADE>
	</Row>
	<Row>
		<Depth>33.2</Depth>
		<DENB>2.42</DENB>
		<CADE>113.24</CADE>
	</Row>
	<Row>
		<Depth>33.3</Depth>
		<DENB>2.41</DENB>
		<CADE>113.07</CADE>
	</Row>
	<Row>
		<Depth>33.4</Depth>
		<DENB>2.41</DENB>
		<CADE>112.69</CADE>
	</Row>
	<Row>
		<Depth>33.5</Depth>
		<DENB>2.43</DENB>
		<CADE>112.27</CADE>
	</Row>
	<Row>
		<Depth>33.6</Depth>
		<DENB>2.44</DENB>
		<CADE>111.75</CADE>
	</Row>
	<Row>
		<Depth>33.7</Depth>
		<DENB>2.43</DENB>
		<CADE>111.36</CADE>
	</Row>
	<Row>
		<Depth>33.8</Depth>
		<DENB>2.41</DENB>
		<CADE>111.01</CADE>
	</Row>
	<Row>
		<Depth>33.9</Depth>
		<DENB>2.38</DENB>
		<CADE>110.9</CADE>
	</Row>
	<Row>
		<Depth>34</Depth>
		<DENB>2.36</DENB>
		<CADE>110.85</CADE>
	</Row>
	<Row>
		<Depth>34.1</Depth>
		<DENB>2.34</DENB>
		<CADE>110.66</CADE>
	</Row>
	<Row>
		<Depth>34.2</Depth>
		<DENB>2.34</DENB>
		<CADE>110.25</CADE>
	</Row>
	<Row>
		<Depth>34.3</Depth>
		<DENB>2.37</DENB>
		<CADE>109.89</CADE>
	</Row>
	<Row>
		<Depth>34.4</Depth>
		<DENB>2.38</DENB>
		<CADE>109.7</CADE>
	</Row>
	<Row>
		<Depth>34.5</Depth>
		<DENB>2.38</DENB>
		<CADE>109.7</CADE>
	</Row>
	<Row>
		<Depth>34.6</Depth>
		<DENB>2.38</DENB>
		<CADE>109.69</CADE>
	</Row>
	<Row>
		<Depth>34.7</Depth>
		<DENB>2.38</DENB>
		<CADE>109.68</CADE>
	</Row>
	<Row>
		<Depth>34.8</Depth>
		<DENB>2.4</DENB>
		<CADE>109.69</CADE>
	</Row>
	<Row>
		<Depth>34.9</Depth>
		<DENB>2.41</DENB>
		<CADE>109.68</CADE>
	</Row>
	<Row>
		<Depth>35</Depth>
		<DENB>2.42</DENB>
		<CADE>109.62</CADE>
	</Row>
	<Row>
		<Depth>35.1</Depth>
		<DENB>2.41</DENB>
		<CADE>109.32</CADE>
	</Row>
	<Row>
		<Depth>35.2</Depth>
		<DENB>2.41</DENB>
		<CADE>108.88</CADE>
	</Row>
	<Row>
		<Depth>35.3</Depth>
		<DENB>2.4</DENB>
		<CADE>108.18</CADE>
	</Row>
	<Row>
		<Depth>35.4</Depth>
		<DENB>2.39</DENB>
		<CADE>107.32</CADE>
	</Row>
	<Row>
		<Depth>35.5</Depth>
		<DENB>2.4</DENB>
		<CADE>106.63</CADE>
	</Row>
	<Row>
		<Depth>35.6</Depth>
		<DENB>2.41</DENB>
		<CADE>106.24</CADE>
	</Row>
	<Row>
		<Depth>35.7</Depth>
		<DENB>2.43</DENB>
		<CADE>106.25</CADE>
	</Row>
	<Row>
		<Depth>35.8</Depth>
		<DENB>2.44</DENB>
		<CADE>106.26</CADE>
	</Row>
	<Row>
		<Depth>35.9</Depth>
		<DENB>2.43</DENB>
		<CADE>106.29</CADE>
	</Row>
	<Row>
		<Depth>36</Depth>
		<DENB>2.44</DENB>
		<CADE>106.39</CADE>
	</Row>
	<Row>
		<Depth>36.1</Depth>
		<DENB>2.43</DENB>
		<CADE>106.81</CADE>
	</Row>
	<Row>
		<Depth>36.2</Depth>
		<DENB>2.43</DENB>
		<CADE>107.44</CADE>
	</Row>
	<Row>
		<Depth>36.3</Depth>
		<DENB>2.41</DENB>
		<CADE>108.04</CADE>
	</Row>
	<Row>
		<Depth>36.4</Depth>
		<DENB>2.4</DENB>
		<CADE>108.33</CADE>
	</Row>
	<Row>
		<Depth>36.5</Depth>
		<DENB>2.4</DENB>
		<CADE>108.41</CADE>
	</Row>
	<Row>
		<Depth>36.6</Depth>
		<DENB>2.41</DENB>
		<CADE>108.45</CADE>
	</Row>
	<Row>
		<Depth>36.7</Depth>
		<DENB>2.41</DENB>
		<CADE>108.46</CADE>
	</Row>
	<Row>
		<Depth>36.8</Depth>
		<DENB>2.42</DENB>
		<CADE>108.46</CADE>
	</Row>
	<Row>
		<Depth>36.9</Depth>
		<DENB>2.42</DENB>
		<CADE>108.43</CADE>
	</Row>
	<Row>
		<Depth>37</Depth>
		<DENB>2.43</DENB>
		<CADE>108.43</CADE>
	</Row>
	<Row>
		<Depth>37.1</Depth>
		<DENB>2.42</DENB>
		<CADE>108.42</CADE>
	</Row>
	<Row>
		<Depth>37.2</Depth>
		<DENB>2.43</DENB>
		<CADE>108.44</CADE>
	</Row>
	<Row>
		<Depth>37.3</Depth>
		<DENB>2.43</DENB>
		<CADE>108.45</CADE>
	</Row>
	<Row>
		<Depth>37.4</Depth>
		<DENB>2.45</DENB>
		<CADE>108.45</CADE>
	</Row>
	<Row>
		<Depth>37.5</Depth>
		<DENB>2.44</DENB>
		<CADE>108.44</CADE>
	</Row>
	<Row>
		<Depth>37.6</Depth>
		<DENB>2.43</DENB>
		<CADE>108.38</CADE>
	</Row>
	<Row>
		<Depth>37.7</Depth>
		<DENB>2.43</DENB>
		<CADE>108.3</CADE>
	</Row>
	<Row>